package main

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func Test_longestPalindromeBest(t *testing.T) {
	assert.EqualValues(t, "aaabbbaaabbbaaa", longestPalindromeBest("aaabbbaaabbbaaa"))
	assert.EqualValues(t, "geeksskeeg", longestPalindromeBest("forgeeksskeegfor"))
	assert.EqualValues(t, "", longestPalindromeBest(""))
	assert.EqualValues(t, "a", longestPalindromeBest("a"))
	assert.EqualValues(t, "bb", longestPalindromeBest("bb"))
	assert.EqualValues(t, "ccc", longestPalindromeBest("ccc"))
	assert.EqualValues(t, "bab", longestPalindromeBest("babad"))
	assert.EqualValues(t, "ranynar", longestPalindromeBest("civilwartestingwhetherthatnaptionoranynartionsoconceivedandsodedicatedcanlongendureWeareqmetonagreatbattlefiemldoftzhatwarWehavecometodedicpateaportionofthatfieldasafinalrestingplaceforthosewhoheregavetheirlivesthatthatnationmightliveItisaltogetherfangandproperthatweshoulddothisButinalargersensewecannotdedicatewecannotconsecratewecannothallowthisgroundThebravelmenlivinganddeadwhostruggledherehaveconsecrateditfaraboveourpoorponwertoaddordetractTgheworldadswfilllittlenotlenorlongrememberwhatwesayherebutitcanneverforgetwhattheydidhereItisforusthelivingrathertobededicatedheretotheulnfinishedworkwhichtheywhofoughtherehavethusfarsonoblyadvancedItisratherforustobeherededicatedtothegreattdafskremainingbeforeusthatfromthesehonoreddeadwetakeincreaseddevotiontothatcauseforwhichtheygavethelastpfullmeasureofdevotionthatweherehighlyresolvethatthesedeadshallnothavediedinvainthatthisnationunsderGodshallhaveanewbirthoffreedomandthatgovernmentofthepeoplebythepeopleforthepeopleshallnotperishfromtheearth"))
}
